stages:
  - docker
  - deploy
  - docker-prd
  - deploy-prd

variables:
  DOCKER_HOST: tcp://localhost:2375/
  IMAGE: $CI_ALI_REGISTRY_DOMAIN/masa/masa-blazor-pro:0.0.$CI_PIPELINE_ID
  IMAGE_PRD: $CI_ALI_REGISTRY_DOMAIN/masa/masa-blazor-pro:$CI_COMMIT_TAG

docker:
  image: docker:17.05.0
  stage: docker
  only:
    - develop
  services:
    - name: $CI_ALI_REGISTRY_DOMAIN/masa/library:docker-17.05.01-dind
  script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN
    - docker build --force-rm  -f ./Masa.Blazor.Pro/Dockerfile -t $IMAGE .
    - docker push $IMAGE
  retry: 2

deploy:
  image: $CI_ALI_REGISTRY_DOMAIN/masa/kubectl:1.17.2-masa-ack-dev
  stage: deploy
  only:
    - develop
  script:
    - kubectl set image deployment/masa-blazor-pro masa-blazor-pro=$IMAGE -n masa-blazor
  retry: 2

docker-prd:
  image: docker:17.05.0
  stage: docker-prd
  only:
    - tags
  services:
    - name: $CI_ALI_REGISTRY_DOMAIN/masa/library:docker-17.05.01-dind
  script:
    - docker login -u $CI_ALI_REGISTRY_USER -p $CI_ALI_REGISTRY_PASSWD $CI_ALI_REGISTRY_DOMAIN
    - docker build --force-rm  -f ./Masa.Blazor.Pro/Dockerfile -t $IMAGE_PRD .
    - docker push $IMAGE_PRD
  retry: 2

deploy-prd:
  image: $CI_ALI_REGISTRY_DOMAIN/masa/kubectl:1.20.1-masa-blazor-prd
  stage: deploy-prd
  only:
    - tags
  script:
    - kubectl set image deployment/masa-blazor-pro masa-blazor-pro=$IMAGE_PRD -n masa-blazor
  retry: 2  
